### ISSUE TITLE
Warning for JSON file

### ISSUE THREAD

**Issue by zakandrewking** [aebrahim/cobra_sbml_validator#2]
For new JSON files, we get this warning:

```
iAF1260b.json - 0 errors and 1 warning
Warning: reaction 'BIOMASS_Ec_iAF1260_core_59p81M' is not balanced. Should it be annotated as a biomass reaction?
objective value: 0.736700938864881
```

**Comment by aebrahim** [comment]
I don't think this is a bug. The JSON model should have the appropriate sbo
term specified for the biomass reaction (in the annotation field)
On May 11, 2016 08:14, "Zachary A. King" notifications@github.com wrote:

For new JSON files, we get this warning:

iAF1260b.json - 0 errors and 1 warning
Warning: reaction 'BIOMASS_Ec_iAF1260_core_59p81M' is not balanced.
Should it be annotated as a biomass reaction?
objective value: 0.736700938864881

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
https://github.com/aebrahim/cobra_sbml_validator/issues/2

**Comment by zakandrewking** [comment]
OK. I'll move it over to bigg_models

**Comment by aebrahim** [comment]
I think this is a result of the fact that the JSON export happens before
polishing
